## Transformers library in huggingface

In [2]:
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [3]:
prompt = "what is Machine Learning"
output = pipe(prompt)
# does not need a tokenizer

[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

In [4]:
print(output[0]['generated_text'])

what is Machine Learning like?

Machine learning is a term from the book of the same name by Richard Moore. It is the idea that any machine can learn anything it wants from a set of data, but that the data must be consistent in the way it has been trained. Machine learning is also called information processing, or "information processing" because it provides the basis for any system that can be trained.

Learning a system is like learning a word by hand. Different words are learned differently, but many of these same systems are working at the same time. Different systems are learning different words differently. This system is learning what you want to do. It is also learning the difference between words you want to say and what you like to say or what you like.

The Machine Learning Toolkit

This is a big part of the experience of Machine Learning. It is the system that is being trained and trained to learn what you want to say.

It is not a machine learning toolkit. Machine learning is a toolkit, but it is not a toolkit in any way.

Machine learning is a way of knowing what you want to say. It is learning if you want to say what you want to say. It is learning if you want to

In [5]:
from transformers import AutoTokenizer, AutoModelForCausalLM
# needs to tokenizer
tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [6]:
from transformers import AutoTokenizer

In [7]:
tokenizer = AutoTokenizer.from_pretrained('gpt2')

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [8]:
tokenizer

GPT2Tokenizer(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})

In [9]:
scentence = "unsure" # divided into syllable/tokens
input_ids = tokenizer(scentence, return_tensors="pt")['input_ids']
input_ids

tensor([[13271,   495]])

In [10]:
tokenizer.decode(input_ids[0])

'unsure'

In [11]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
inputs = tokenizer(word, return_tensors='pt')['input_ids']
inputs

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])

In [12]:
tokenizer.decode(inputs[0])

'pneumonoultramicroscopicsilicovolcanoconiosis'

In [13]:
from transformers import AutoModelForCausalLM

gpt2 = AutoModelForCausalLM.from_pretrained('gpt2')

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [14]:
gpt2

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [15]:
# give the next word
scentence = "I like machine learning to enhance"
tokens = tokenizer(scentence, return_tensors='pt').input_ids
outputs = gpt2(tokens).logits[0, -1]
tokenizer.decode(outputs.argmax())

' our'

In [16]:
import torch
import torch.nn.functional as F

In [17]:
# top k highest possibilities from the next values
scentence = "i learn machine learning to destroy human"
tokens = tokenizer(scentence, return_tensors='pt').input_ids
outputs = gpt2(tokens).logits[0, -1]
final_logits = torch.topk(outputs,10)
for index in final_logits.indices:
    print(tokenizer.decode(index))

 beings
 life
 civilization
 intelligence
 lives
 minds
 knowledge
 society
 enemies
 labor

In [18]:
def greedy_decode(logits):
  #return token index with max probability
  return torch.argmax(logits,dim=-1)

greedy_decode(outputs)

tensor(9791)

In [19]:
def top_k(logits, k = 10):
  # keeps only top k logits normalize them into probabilities
  # then sample 1 token from the filtered distribution
  values, indices = torch.topk(logits, k)
  probs = F.softmax(values, dim = -1)
  samples = torch.multinomial(probs, 1)
  return indices[samples]

tokenizer.decode(top_k(outputs))

' life'

In [20]:
def top_p(logits, p = 0.9):
  # sort tokens by prob. keep smallest no whose cumulative prob value exceeds p,
  # then sameple 1 token
  sorted_logits, sorted_indices = torch.sort(logits, descending=True)
  sorted_probs = F.softmax(sorted_logits, dim = -1)
  cumulative_probs = sorted_probs.cumsum(dim = -1)

  # mask tokens not being considered
  mask = cumulative_probs > p
  sorted_logits[mask] = float('-inf')

  # sample from filtered logits
  filtered_probs = F.softmax(sorted_logits, dim = -1)
  sampled = torch.multinomial(filtered_probs, 1)

  # return token index in original vocabulary
  return sorted_indices[sampled]

tokenizer.decode(top_p(outputs))

' existence'

In [21]:
def temperature_sampling(logits, temperature =0.8):
  # scales logits by temp before sampling
  # lower temp  -> sharper more deterministic distributuin
  # higher temp -> flatter temp distribution

  scaled = logits / temperature
  probs = F.softmax(scaled, dim = -1)
  return torch.multinomial(probs, 1)

tokenizer.decode(temperature_sampling(outputs))

' thoughts'

In [22]:
def random_sampling(logits):
  # samples directly from softmax dist without filtering

  probs = F.softmax(logits, dim = -1)
  return torch.multinomial(probs, 1)

tokenizer.decode(random_sampling(outputs))

' trafficking'

In [23]:
scentence = "I learn Maching Learning to enhance"
tokens_ids = tokenizer(scentence, return_tensors='pt').input_ids
outputs = gpt2(tokens_ids).logits[0, -1]
outputs = torch.softmax(outputs, dim = -1)

top10 = torch.topk(outputs, k = 10)

for index, values in zip(top10.indices, top10.values):
  print(f"{tokenizer.decode(index)} --  {values:.1%}")

 your --  35.9%
 the --  9.0%
 my --  7.6%
 our --  2.8%
 learning --  2.1%
 a --  1.1%
 their --  1.0%
 and --  1.0%
 self --  0.8%
 one --  0.7%

## sentimant analysis

In [24]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 21.0MB

plain_text/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 20.5MB

plain_text/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

plain_text/unsupervised-00000-of-00001.p(…): reconstructing file:   0%|          |  0.00B / 42.0MB

plain_text/unsupervised-00000-of-00001.p(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [25]:
type(ds)

datasets.dataset_dict.DatasetDict

In [26]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [27]:
ds["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [28]:
import pandas as pd

In [29]:
ds['train'].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [30]:
my_dataset_df = ds["train"].to_pandas()

In [31]:
my_dataset_df['text']

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [32]:
len(my_dataset_df["text"])

25000

In [57]:
from transformers import pipeline

In [33]:
classifier = pipeline("sentiment-analysis")

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [34]:
classifier("this day is great")

[{'label': 'POSITIVE', 'score': 0.9998873472213745}]

In [35]:
classifier("no thanks")

[{'label': 'NEGATIVE', 'score': 0.9936198592185974}]

In [36]:
def score(text):
  return classifier(text[:500])[0]['label']

score('hi')

'POSITIVE'

In [39]:
my_dataset_df['model_prediction'] = my_dataset_df['text'].apply(score)

KeyboardInterrupt:

In [ ]:
my_dataset_df

In [40]:
from transformers import pipeline

pipe = pipeline("sentiment-analysis", model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  438MB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [41]:
text = "the company reported a strong increase in quarterly revenue, exceeding market expectations"

In [43]:
pipe(text)

[{'label': 'positive', 'score': 0.9542218446731567}]

In [44]:
pipe("shares fell after the firm reported the lower than exporeted earnings")

[{'label': 'negative', 'score': 0.963023841381073}]

## Name entity recognition

In [68]:
ner = pipeline("ner")

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [69]:
scentence = "Apple announced record earnings in the United States on Monday"

In [70]:
results = ner(scentence)
print(results)

[{'entity': 'I-ORG', 'score': np.float32(0.99911004), 'index': 1, 'word': 'Apple', 'start': 0, 'end': 5}, {'entity': 'I-LOC', 'score': np.float32(0.99967754), 'index': 7, 'word': 'United', 'start': 39, 'end': 45}, {'entity': 'I-LOC', 'score': np.float32(0.9996001), 'index': 8, 'word': 'States', 'start': 46, 'end': 52}]

## Question Answering

In [72]:
qa = pipeline("document-question-answering")

[transformers] No model was supplied, defaulted to impira/layoutlm-document-qa and revision beed3c4.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/789 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  511MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/205 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/315 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

## Machine Translation

In [82]:
mod = pipeline("Translation_en_to_fr")

KeyError: "Unknown task Translation_en_to_fr, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

TypeError: DocumentQuestionAnsweringPipeline.__call__() missing 1 required positional argument: 'image'

## Audio Processing

In [ ]:
#